// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Elysia from "elysia";
import * as Cors from "@elysiajs/cors";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as ConfigLoaderResMjs from "./config-loader.res.mjs";
import * as PostgresClientResMjs from "./db/postgres-client.res.mjs";

let Elysia$1 = {};

let Cors$1 = {};

function makeClient(prim) {
  return new PostgresClientResMjs.PostgresClient(prim);
}

let Postgres = {
  makeClient: makeClient
};

function loadConfig(prim) {
  return ConfigLoaderResMjs.loadConfig();
}

function make() {
  return {
    config: undefined,
    db: undefined,
    app: new Elysia.Elysia()
  };
}

function setupRoutes(self) {
  return self.app.use(Cors.cors()).group("/api", app => app.get("/health", param => ({
    status: "ok",
    timestamp: Date.now()
  })).group("/workflows", app => app.get("/", param => ([])).get("/:id", param => ({}))));
}

async function initialize(self) {
  console.log("Initializing Dashboard Server...");
  let config = await ConfigLoaderResMjs.loadConfig();
  self.config = config;
  let db = new PostgresClientResMjs.PostgresClient(config.database);
  self.db = Primitive_option.some(db);
  await db.connect();
  setupRoutes(self);
  let port = config.port;
  self.app.listen(port);
  console.log(`Dashboard API listening on port ` + port.toString());
}

let DashboardServer = {
  make: make,
  setupRoutes: setupRoutes,
  initialize: initialize
};

let server = make();

initialize(server);

export {
  Elysia$1 as Elysia,
  Cors$1 as Cors,
  Postgres,
  loadConfig,
  DashboardServer,
  server,
}
/* server Not a pure module */
