// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Core__Int from "@rescript/core/src/Core__Int.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

let Path$1 = {};

let Fs$1 = {};

function parseSimpleTOML(content) {
  let result = {};
  let currentSection = {
    contents: result
  };
  let lines = content.split("\n");
  lines.forEach(line => {
    let trimmed = line.trim();
    if (trimmed.startsWith("#") || trimmed === "") {
      return;
    }
    if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
      let sectionName = trimmed.substring(1, trimmed.length - 1 | 0);
      let section = {};
      result[sectionName] = section;
      currentSection.contents = section;
      return;
    }
    let parts = trimmed.split("=");
    if (parts.length !== 2) {
      return;
    }
    let key = Belt_Array.getExn(parts, 0).trim();
    let value = Belt_Array.getExn(parts, 1).trim();
    let jsonValue;
    if (value.startsWith("\"") && value.endsWith("\"")) {
      jsonValue = value.substring(1, value.length - 1 | 0);
    } else if (value === "true") {
      jsonValue = true;
    } else if (value === "false") {
      jsonValue = false;
    } else {
      let n = Core__Int.fromString(value, undefined);
      jsonValue = n !== undefined ? n : value;
    }
    currentSection.contents[key] = jsonValue;
  });
  return result;
}

async function loadConfig(configPath) {
  let path = configPath !== undefined ? configPath : Path.join(import.meta.dirname, "../dashboard-config.toml");
  if (Fs.existsSync(path)) {
    return parseSimpleTOML(Fs.readFileSync(path, "utf-8"));
  } else {
    return {
      server: {
        port: 4000,
        host: "localhost"
      },
      database: {
        host: "localhost",
        port: 5432
      }
    };
  }
}

export {
  Path$1 as Path,
  Fs$1 as Fs,
  parseSimpleTOML,
  loadConfig,
}
/* fs Not a pure module */
