#!/bin/bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath) <jonathan.jewell@open.ac.uk>
#
# Project Wharf — Local end-to-end test
# ======================================
# Downloads WordPress, generates wp-config.php, copies the adapter plugin,
# builds containers, and starts the full stack.
#
# Usage: cd deploy && bash local-test.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOCAL_DIR="$SCRIPT_DIR/wharf-local"
HTML_DIR="$LOCAL_DIR/html"
DB_DIR="$LOCAL_DIR/db"

DB_NAME="wordpress"
DB_USER="wordpress"
DB_PASS="${MARIADB_PASSWORD:-wharf-demo-pass-2026}"

echo "======================================"
echo "  Project Wharf — Local E2E Test"
echo "======================================"
echo ""

# -------------------------------------------------------------------------
# 1. Create local directories
# -------------------------------------------------------------------------
echo "[1/7] Creating local directories..."
mkdir -p "$HTML_DIR" "$DB_DIR"
echo "  $LOCAL_DIR/{html,db} created"

# -------------------------------------------------------------------------
# 2. Download WordPress if not present
# -------------------------------------------------------------------------
echo "[2/7] Checking WordPress..."
if [ ! -f "$HTML_DIR/wp-includes/version.php" ]; then
    echo "  Downloading WordPress..."
    curl -sL https://wordpress.org/latest.tar.gz -o /tmp/wordpress-latest.tar.gz
    tar xzf /tmp/wordpress-latest.tar.gz -C /tmp/
    cp -a /tmp/wordpress/* "$HTML_DIR/"
    rm -rf /tmp/wordpress /tmp/wordpress-latest.tar.gz
    echo "  WordPress downloaded"
else
    echo "  WordPress already present"
fi

# -------------------------------------------------------------------------
# 3. Fetch real salt keys from WordPress API
# -------------------------------------------------------------------------
echo "[3/7] Fetching WordPress salt keys..."
SALT_KEYS=$(curl -sf https://api.wordpress.org/secret-key/1.1/salt/ 2>/dev/null || true)
if [ -z "$SALT_KEYS" ]; then
    echo "  WARNING: Could not fetch salt keys from api.wordpress.org"
    echo "  Using fallback random values"
    # Generate random salts as fallback
    gen_salt() { head -c 48 /dev/urandom | base64 | tr -d '\n'; }
    SALT_KEYS=$(cat <<SALTS
define('AUTH_KEY',         '$(gen_salt)');
define('SECURE_AUTH_KEY',  '$(gen_salt)');
define('LOGGED_IN_KEY',    '$(gen_salt)');
define('NONCE_KEY',        '$(gen_salt)');
define('AUTH_SALT',        '$(gen_salt)');
define('SECURE_AUTH_SALT', '$(gen_salt)');
define('LOGGED_IN_SALT',   '$(gen_salt)');
define('NONCE_SALT',       '$(gen_salt)');
SALTS
)
fi

# -------------------------------------------------------------------------
# 4. Generate wp-config.php — DB_HOST points to agent (proxy), NOT db
# -------------------------------------------------------------------------
echo "[4/7] Writing wp-config.php (DB_HOST = agent:3306)..."
cat > "$HTML_DIR/wp-config.php" << WPEOF
<?php
// Generated by Project Wharf local-test.sh
// DB traffic is routed through yacht-agent's SQL firewall proxy.

define('DB_NAME',     '$DB_NAME');
define('DB_USER',     '$DB_USER');
define('DB_PASSWORD', '$DB_PASS');
define('DB_HOST',     'agent:3306');  // yacht-agent proxy — NOT direct DB
define('DB_CHARSET',  'utf8mb4');
define('DB_COLLATE',  '');

// Security keys (fetched from api.wordpress.org)
$SALT_KEYS

\$table_prefix = 'wp_';

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
define('DISALLOW_FILE_EDIT', true);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}
require_once ABSPATH . 'wp-settings.php';
WPEOF
echo "  wp-config.php written"

# -------------------------------------------------------------------------
# 5. Copy adapter plugin
# -------------------------------------------------------------------------
echo "[5/7] Copying Wharf adapter plugin..."
PLUGIN_SRC="$REPO_ROOT/adapters/wordpress-wharf"
PLUGIN_DST="$HTML_DIR/wp-content/plugins/wharf-adapter"

mkdir -p "$PLUGIN_DST"
cp "$PLUGIN_SRC/wharf-adapter.php" "$PLUGIN_DST/"
echo "  Plugin copied to wp-content/plugins/wharf-adapter/"

# -------------------------------------------------------------------------
# 6. Build containers
# -------------------------------------------------------------------------
echo "[6/7] Building containers..."
cd "$SCRIPT_DIR"
podman compose build
echo "  Containers built"

# -------------------------------------------------------------------------
# 7. Start the stack
# -------------------------------------------------------------------------
echo "[7/7] Starting stack..."
podman compose up -d

echo ""
echo "  Waiting for services to become healthy..."

# Wait for agent health
for i in $(seq 1 30); do
    if curl -sf http://localhost:9001/health >/dev/null 2>&1; then
        echo "  Agent: healthy"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "  WARNING: Agent health check timed out"
    fi
    sleep 2
done

# Wait for OLS
for i in $(seq 1 20); do
    if curl -sf http://localhost:8080/ >/dev/null 2>&1; then
        echo "  Web: healthy"
        break
    fi
    if [ "$i" -eq 20 ]; then
        echo "  WARNING: Web server health check timed out"
    fi
    sleep 2
done

echo ""
echo "======================================"
echo "  Stack Running!"
echo "======================================"
echo ""
echo "  WordPress:  http://localhost:8080"
echo "  Agent API:  http://localhost:9001/health"
echo "  Agent Stats: http://localhost:9001/stats"
echo ""
echo "  Next steps:"
echo "    1. Visit http://localhost:8080 to run WordPress setup wizard"
echo "    2. Activate 'Wharf Security Adapter' plugin in wp-admin"
echo "    3. Run: bash verify-sqli.sh  (prove SQL injection is blocked)"
echo ""
echo "  Tear down:"
echo "    cd deploy && podman compose down"
echo "    rm -rf wharf-local/  (to remove all data)"
echo ""
