#!/bin/bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath) <jonathan.jewell@open.ac.uk>
#
# Project Wharf — First-run deployment setup
# ===========================================
# Creates directory structure, generates keypairs, pulls images, starts stack.
#
# Usage: sudo ./setup.sh [--domain example.com]

set -euo pipefail

WHARF_ROOT="${WHARF_ROOT:-/opt/wharf}"
DOMAIN="${1:---domain}"
DOMAIN="${2:-localhost}"

# Parse --domain flag
if [ "$DOMAIN" = "--domain" ] && [ -n "${2:-}" ]; then
    DOMAIN="$2"
elif [ "$1" != "--domain" ] && [ -n "${1:-}" ]; then
    DOMAIN="$1"
fi

echo "======================================"
echo "  Project Wharf — Deployment Setup"
echo "======================================"
echo "  Root:   $WHARF_ROOT"
echo "  Domain: $DOMAIN"
echo ""

# 1. Create directory structure
echo "[1/5] Creating directory structure..."
mkdir -p "$WHARF_ROOT/sites/$DOMAIN/html"
mkdir -p "$WHARF_ROOT/sites/$DOMAIN/uploads"
mkdir -p "$WHARF_ROOT/config/keys"
mkdir -p "$WHARF_ROOT/integrity"
mkdir -p "$WHARF_ROOT/certs"
mkdir -p "$WHARF_ROOT/data/mysql"

# Restrictive permissions on key store
chmod 700 "$WHARF_ROOT/config/keys"

echo "  Directories created at $WHARF_ROOT/"

# 2. Generate yacht-agent configuration
echo "[2/5] Writing agent configuration..."
cat > "$WHARF_ROOT/config/yacht-agent.toml" << TOMLEOF
# Yacht Agent Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

[db_proxy]
protocol = "mysql"
listen_port = 3306
shadow_host = "db"
shadow_port = 3306

[api]
port = 9001
metrics_enabled = true

[firewall]
mode = "nftables"
tcp_ports = [80, 443, 9001]

site_root = "/var/www/html"
key_store_dir = "/etc/wharf/keys"
signature_scheme = "ml-dsa-87-only"
TOMLEOF

echo "  Config written to $WHARF_ROOT/config/yacht-agent.toml"

# 3. Pull container images (or build locally)
echo "[3/5] Pulling container images..."
if command -v podman &>/dev/null; then
    RUNTIME="podman"
elif command -v docker &>/dev/null; then
    RUNTIME="docker"
else
    echo "  ERROR: Neither podman nor docker found. Install podman first."
    exit 1
fi

# Try pulling from GHCR, fall back to local build
if $RUNTIME pull ghcr.io/hyperpolymath/yacht-agent:latest 2>/dev/null; then
    echo "  Pulled yacht-agent from GHCR"
else
    echo "  GHCR pull failed — building locally..."
    if [ -f ../infra/containers/Containerfile.agent ]; then
        $RUNTIME build -t yacht-agent:latest -f ../infra/containers/Containerfile.agent ..
    else
        echo "  ERROR: No Containerfile found. Run from deploy/ directory."
        exit 1
    fi
fi

# 4. Download WordPress (if site root is empty)
echo "[4/5] Checking WordPress installation..."
if [ ! -f "$WHARF_ROOT/sites/$DOMAIN/html/wp-config.php" ]; then
    echo "  No WordPress found. Downloading..."
    curl -sL https://wordpress.org/latest.tar.gz | tar xz -C /tmp/
    cp -r /tmp/wordpress/* "$WHARF_ROOT/sites/$DOMAIN/html/"
    rm -rf /tmp/wordpress

    # Write wp-config.php pointing DB through the yacht-agent proxy
    cat > "$WHARF_ROOT/sites/$DOMAIN/html/wp-config.php" << 'WPEOF'
<?php
// SPDX-License-Identifier: GPL-2.0-or-later
// WordPress configuration — DB routed through yacht-agent proxy

define('DB_NAME', 'wordpress');
define('DB_USER', 'wordpress');
define('DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD') ?: 'changeme');
define('DB_HOST', 'agent:3306');  // Yacht-agent proxy, NOT direct DB
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

// Security keys — generate at https://api.wordpress.org/secret-key/1.1/salt/
define('AUTH_KEY',         'put-your-unique-phrase-here');
define('SECURE_AUTH_KEY',  'put-your-unique-phrase-here');
define('LOGGED_IN_KEY',    'put-your-unique-phrase-here');
define('NONCE_KEY',        'put-your-unique-phrase-here');
define('AUTH_SALT',        'put-your-unique-phrase-here');
define('SECURE_AUTH_SALT', 'put-your-unique-phrase-here');
define('LOGGED_IN_SALT',   'put-your-unique-phrase-here');
define('NONCE_SALT',       'put-your-unique-phrase-here');

$table_prefix = 'wp_';
define('WP_DEBUG', false);
define('DISALLOW_FILE_EDIT', true);  // No editing plugins/themes from wp-admin
define('DISALLOW_FILE_MODS', true);  // No installing plugins from wp-admin

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}
require_once ABSPATH . 'wp-settings.php';
WPEOF

    echo "  WordPress downloaded and configured"
    echo "  IMPORTANT: Edit wp-config.php and add real security keys!"
else
    echo "  WordPress already installed"
fi

# 5. Generate initial integrity manifest
echo "[5/5] Generating integrity manifest..."
if command -v wharf &>/dev/null; then
    wharf integrity generate --path "$WHARF_ROOT/sites/$DOMAIN/html" \
        --output "$WHARF_ROOT/integrity/$DOMAIN.manifest.json"
    echo "  Manifest saved to $WHARF_ROOT/integrity/$DOMAIN.manifest.json"
else
    echo "  wharf CLI not found — skipping manifest generation"
    echo "  Install later: cargo install --path bin/wharf-cli"
fi

echo ""
echo "======================================"
echo "  Setup Complete!"
echo "======================================"
echo ""
echo "  Next steps:"
echo "  1. Edit $WHARF_ROOT/config/yacht-agent.toml if needed"
echo "  2. Set DB password: export WORDPRESS_DB_PASSWORD=<your-password>"
echo "  3. Start the stack: selur-compose -f infra/selur-compose.yaml up -d"
echo "     (or: podman compose -f infra/selur-compose.yaml up -d)"
echo "  4. Visit http://$DOMAIN:8080 to finish WordPress setup"
echo "  5. From your local machine: wharf moor $DOMAIN"
echo ""
echo "  Monitoring:"
echo "    Health: curl http://localhost:9001/health"
echo "    Stats:  curl http://localhost:9001/stats"
echo "    Metrics: curl http://localhost:9001/metrics"
echo ""
