;; SPDX-License-Identifier: PMPL-1.0-or-later
(state (metadata (version "0.1.0") (last-updated "2026-02-14") (status active))
  (project-context
    (name "project-wharf")
    (purpose "Sovereign Web Hypervisor — immutable CMS infrastructure with offline admin (Wharf) and online runtime (Yacht)")
    (completion-percentage 95))
  (route-to-mvp
    (milestone "crypto-overhaul" (status complete) (description "Ed448 + ML-DSA-87 hybrid signatures, SHAKE3-512, XChaCha20-Poly1305, HKDF, Argon2id"))
    (milestone "http-mooring-client" (status complete) (description "MooringClient HTTP API: init → verify → rsync → commit"))
    (milestone "identity-file" (status complete) (description "SSH identity resolution: yacht → fleet → ~/.ssh/id_ed448 → agent"))
    (milestone "container-compliance" (status complete) (description "Chainguard bases, Containerfile naming, selur-compose orchestration"))
    (milestone "demo-script" (status complete) (description "End-to-end mooring + SQL injection blocking + file tampering detection"))
    (milestone "production-hardening" (status complete) (description "Production hardening milestone")
      (sub-milestone "keypair-persistence" (status complete) (description "Persistent hybrid keypairs for CLI and yacht-agent with file permissions"))
      (sub-milestone "ebpf-loader" (status complete) (description "Full XDP kernel program + userspace loader in crates/wharf-ebpf/"))
      (sub-milestone "database-proxy" (status complete) (description "Full AST parser via sqlparser 0.39 in db_policy.rs"))
      (sub-milestone "certificate-management" (status complete) (description "1024-line Nebula module in nebula.rs with CA, cert signing, IP allocation, revocation"))
      (sub-milestone "metrics" (status complete) (description "Prometheus metrics and stats endpoints wired to real counters"))
      (sub-milestone "http-resilience" (status complete) (description "Timeouts, connection pooling on mooring HTTP client"))
      (sub-milestone "integrity-verification" (status complete) (description "Yacht agent mooring verify wired to BLAKE3 manifest verification"))
      (sub-milestone "ed448-audit" (status pending) (description "ed448-goldilocks v0.14.0-pre.10 needs third-party audit before production"))))
    (milestone "v1.0-shipping" (status complete) (description "V1.0 shipping preparation")
      (sub-milestone "signature-scheme-flag" (status complete) (description "Feature-flag ed448: MlDsa87Only default, Hybrid opt-in"))
      (sub-milestone "sqli-smoke-tests" (status complete) (description "19 integration tests proving AST proxy blocks WordPress attack patterns"))
      (sub-milestone "deployment-package" (status complete) (description "setup.sh, DEPLOY.adoc, selur-compose orchestration"))
      (sub-milestone "hack-me-challenge" (status complete) (description "HACK-ME-CHALLENGE.adoc with rules of engagement and technical details"))
      (sub-milestone "wordpress-adapter" (status complete) (description "GPL-2.0 PHP plugin for wp-admin dashboard widget + admin bar indicator"))
      (sub-milestone "systemd-packaging" (status complete) (description "yacht-agent.service with full systemd hardening"))
      (sub-milestone "tooling-enrollment" (status complete) (description "Bot directives, panic-attacker workflow, AI manifest updated")))
    (milestone "local-deployment-proof" (status complete) (description "End-to-end local deployment with podman compose")
      (sub-milestone "containerfile-fixes" (status complete) (description "Fixed Wolfi packages in Containerfile.agent (musl→glibc), yacht-agent runtime stage (static→wolfi-base)"))
      (sub-milestone "wordpress-adapter-fix" (status complete) (description "Fixed stats/status field mismatch — now fetches both /stats and /status endpoints"))
      (sub-milestone "compose-stack" (status complete) (description "3-service compose: MariaDB, yacht-agent proxy, OpenLiteSpeed+WordPress"))
      (sub-milestone "automated-setup" (status complete) (description "local-test.sh: WP download, real salt keys, wp-config.php, adapter plugin, build+start"))
      (sub-milestone "sqli-verification" (status complete) (description "verify-sqli.sh: 6/6 attacks blocked (SELECT passes, INSERT/DROP/ALTER/TRUNCATE/UNION blocked)"))))
  (components
    (component "wharf-core" (path "crates/wharf-core") (role "shared library: crypto, fleet, integrity, mooring, sync"))
    (component "wharf-cli" (path "bin/wharf-cli") (role "offline admin CLI: moor, integrity, fleet management"))
    (component "yacht-agent" (path "bin/yacht-agent") (role "online runtime: HTTP API, DB proxy, firewall, integrity enforcement"))
    (component "wharf-ebpf" (path "crates/wharf-ebpf") (role "eBPF programs for XDP firewall (optional, excluded from default build)"))
    (component "xtask" (path "xtask") (role "build tasks: eBPF compilation")))
  (blockers-and-issues
    (blocker "ed448-goldilocks-pre-release" (severity medium) (description "v0.14.0-pre.10 is unaudited; needs third-party audit before production deployment"))))
