// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(db) {
  return {
    db: db
  };
}

async function getNormative(self, workflowId) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe(`SELECT * FROM baselines WHERE workflow_id = '` + workflowId + `' AND is_normative = true LIMIT 1`);
      return {
        success: false,
        error: {
          code: "NOT_FOUND",
          message: "Normative baseline not found for workflow"
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch baseline"
      }
    };
  }
}

async function list(self, _workflowId) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe("SELECT * FROM baselines");
      return {
        success: true,
        data: [],
        metadata: {
          timestamp: Date.now().toString(),
          pagination: {
            page: 1,
            limit: 20,
            total: 0,
            pages: 1
          }
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch baselines"
      }
    };
  }
}

let BaselineController = {
  make: make,
  getNormative: getNormative,
  list: list
};

export {
  BaselineController,
}
/* No side effect */
