// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(db) {
  return {
    db: db
  };
}

async function list(self, _status) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe("SELECT * FROM executions");
      return {
        success: true,
        data: [],
        metadata: {
          timestamp: Date.now().toString(),
          pagination: {
            page: 1,
            limit: 20,
            total: 0,
            pages: 1
          }
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch executions"
      }
    };
  }
}

async function getStats(self) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe("SELECT COUNT(*) FROM executions");
      return {
        success: true,
        data: {
          total: 0,
          running: 0,
          completed_today: 0,
          failed_today: 0,
          success_rate: 100.0,
          avg_duration_ms: 0.0
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch execution stats"
      }
    };
  }
}

let ExecutionController = {
  make: make,
  list: list,
  getStats: getStats
};

export {
  ExecutionController,
}
/* No side effect */
