// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(db) {
  return {
    db: db
  };
}

async function list(self, _type) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe("SELECT * FROM symbols");
      return {
        success: true,
        data: [],
        metadata: {
          timestamp: Date.now().toString(),
          pagination: {
            page: 1,
            limit: 20,
            total: 0,
            pages: 1
          }
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch symbols"
      }
    };
  }
}

async function search(self, query, _type) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe(`SELECT * FROM symbols WHERE name ILIKE '%` + query + `%'`);
      return {
        success: true,
        data: []
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to search symbols"
      }
    };
  }
}

let SymbolController = {
  make: make,
  list: list,
  search: search
};

export {
  SymbolController,
}
/* No side effect */
