// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PostgresClient from "../../db/PostgresClient.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(db) {
  return {
    db: db
  };
}

async function list(self, _status) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe("SELECT * FROM workflows");
      return {
        success: true,
        data: [],
        metadata: {
          timestamp: Date.now().toString(),
          pagination: {
            page: 1,
            limit: 20,
            total: 0,
            pages: 1
          }
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch workflows"
      }
    };
  }
}

async function create(self, name, manifestPath) {
  try {
    let sql = self.db.sql;
    if (sql !== undefined) {
      await Primitive_option.valFromOption(sql).unsafe(`INSERT INTO workflows (name, manifest_path) VALUES ('` + name + `', '` + manifestPath + `')`);
      return {
        success: false,
        error: {
          code: "ERROR",
          message: "Creation placeholder"
        }
      };
    } else {
      return {
        success: false,
        error: {
          code: "DB_ERROR",
          message: "Not connected"
        }
      };
    }
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to create workflow"
      }
    };
  }
}

async function getSymbols(self, workflowId) {
  try {
    await PostgresClient.PostgresClient.getSymbolsByWorkflow(self.db, workflowId);
    return {
      success: true,
      data: []
    };
  } catch (exn) {
    return {
      success: false,
      error: {
        code: "DB_ERROR",
        message: "Failed to fetch symbols"
      }
    };
  }
}

let WorkflowController = {
  make: make,
  list: list,
  create: create,
  getSymbols: getSymbols
};

export {
  WorkflowController,
}
/* PostgresClient Not a pure module */
