// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "http";
import Express from "express";
import * as Server from "@apollo/server";

let Apollo = {};

let Express$1 = {};

let Http$1 = {};

async function startServer() {
  console.log("🚀 Starting WP Praxis GraphQL Server...");
  let app = Express();
  let httpServer = Http.createServer(app);
  let server = new Server.ApolloServer({
    schema: {},
    plugins: [],
    introspection: true
  });
  await server.start();
  app.get("/health", (_req, res) => {
    ({
        status: "ok",
        timestamp: Date.now()
      });
    ((res.json(payload)));
  });
  let host = "localhost";
  httpServer.listen({
    port: 4000,
    host: host
  }, () => {
    console.log(`🚀 GraphQL API Server ready at http://` + host + `:` + (4000).toString() + `/graphql`);
  });
}

startServer();

export {
  Apollo,
  Express$1 as Express,
  Http$1 as Http,
  startServer,
}
/*  Not a pure module */
