// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by , PLEASE EDIT WITH CARE

import Postgres from "postgres";
import * as Pervasives from "@/runtime/lib/es6/Pervasives.js";
import * as Primitive_option from "@/runtime/lib/es6/Primitive_option.js";

let Types = {};

function make(config) {
  return {
    sql: undefined,
    connected: false,
    config: config
  };
}

async function connect(self) {
  try {
    let sql = Postgres(self.config);
    self.sql = Primitive_option.some(sql);
    await sql.unsafe("SELECT 1 as connected");
    self.connected = true;
    console.log("Postgres connected successfully");
    return;
  } catch (exn) {
    console.error("DB Connection failure");
    return Pervasives.failwith("Database connection failed");
  }
}

async function healthCheck(self) {
  let sql = self.sql;
  if (sql === undefined) {
    return false;
  }
  try {
    await Primitive_option.valFromOption(sql).unsafe("SELECT 1");
    return true;
  } catch (exn) {
    return false;
  }
}

async function getWorkflows(self, _limit, _offset) {
  let sql = self.sql;
  if (sql !== undefined) {
    return await Primitive_option.valFromOption(sql).unsafe("SELECT * FROM workflows ORDER BY updated_at DESC");
  } else {
    return Pervasives.failwith("Not connected");
  }
}

async function getSymbolsByWorkflow(self, workflowId) {
  let sql = self.sql;
  if (sql !== undefined) {
    return await Primitive_option.valFromOption(sql).unsafe(`SELECT s.* FROM symbols s JOIN workflow_symbols ws ON s.id = ws.symbol_id WHERE ws.workflow_id = '` + workflowId + `'`);
  } else {
    return Pervasives.failwith("Not connected");
  }
}

let PostgresClient = {
  make: make,
  connect: connect,
  healthCheck: healthCheck,
  getWorkflows: getWorkflows,
  getSymbolsByWorkflow: getSymbolsByWorkflow
};

export {
  Types,
  PostgresClient,
}
/* postgres Not a pure module */
