// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


let Elysia = {};

let Postgres = {};

function setupHealthRoutes(app, db) {
  return app.group("/health", app => app.get("/", async param => {
    let dbOk = await db.healthCheck();
    let mem = process.memoryUsage();
    return {
      status: dbOk ? "healthy" : "degraded",
      database: dbOk ? "connected" : "disconnected",
      memoryMb: mem.heapUsed / 1024.0 / 1024.0 | 0,
      timestamp: Date.now()
    };
  }).get("/detailed", async param => {
    let dbOk = await db.healthCheck();
    let mem = process.memoryUsage();
    return {
      status: dbOk ? "healthy" : "unhealthy",
      process: {
        uptime: process.uptime(),
        pid: process.pid,
        arch: process.arch
      },
      memory: {
        rss: mem.rss,
        heapTotal: mem.heapTotal,
        heapUsed: mem.heapUsed
      },
      database: {
        connected: dbOk
      }
    };
  }));
}

export {
  Elysia,
  Postgres,
  setupHealthRoutes,
}
/* No side effect */
