// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuditController from "./controllers/AuditController.res.js";
import * as SymbolController from "./controllers/SymbolController.res.js";
import * as BaselineController from "./controllers/BaselineController.res.js";
import * as WorkflowController from "./controllers/WorkflowController.res.js";
import * as ExecutionController from "./controllers/ExecutionController.res.js";

let Elysia = {};

function setupAuditRoutes(app, controller) {
  return app.group("/audits", app => app.get("/", async _ctx => {
    let workflowId = ctx.query.workflow_id;
    return await AuditController.AuditController.list(controller, workflowId);
  }).get("/stats", async param => await AuditController.AuditController.getStats(controller)));
}

function setupBaselineRoutes(app, controller) {
  return app.group("/baselines", app => app.get("/", async _ctx => {
    let workflowId = ctx.query.workflow_id;
    return await BaselineController.BaselineController.list(controller, workflowId);
  }).get("/normative/:workflow_id", async _ctx => {
    let workflowId = ctx.params.workflow_id;
    return await BaselineController.BaselineController.getNormative(controller, workflowId);
  }));
}

function setupExecutionRoutes(app, controller) {
  return app.group("/executions", app => app.get("/", async _ctx => {
    let status = ctx.query.status;
    return await ExecutionController.ExecutionController.list(controller, status);
  }).get("/stats", async param => await ExecutionController.ExecutionController.getStats(controller)));
}

function setupSymbolRoutes(app, controller) {
  return app.group("/symbols", app => app.get("/", async param => await SymbolController.SymbolController.list(controller, undefined)).get("/search", async _ctx => {
    let q = ctx.query.q;
    let type_ = ctx.query.type;
    return await SymbolController.SymbolController.search(controller, q, type_);
  }));
}

function setupWorkflowRoutes(app, controller) {
  return app.group("/workflows", app => app.get("/", async _ctx => {
    let status = ctx.query.status;
    return await WorkflowController.WorkflowController.list(controller, status);
  }).post("/", async _ctx => {
    let name = ctx.body.name;
    let path = ctx.body.manifest_path;
    return await WorkflowController.WorkflowController.create(controller, name, path);
  }).get("/:id/symbols", async _ctx => {
    let id = ctx.params.id;
    return await WorkflowController.WorkflowController.getSymbols(controller, id);
  }));
}

export {
  Elysia,
  setupAuditRoutes,
  setupBaselineRoutes,
  setupExecutionRoutes,
  setupSymbolRoutes,
  setupWorkflowRoutes,
}
/* WorkflowController Not a pure module */
