// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by , PLEASE EDIT WITH CARE


let WebSocket = {};

function make() {
  return {
    connections: new Set(),
    heartbeatInterval: undefined
  };
}

function createMessage(type_, payload) {
  return {
    type: type_,
    payload: payload,
    timestamp: Date.now().toString()
  };
}

function sendToClient(ws, type_, payload) {
  let message = createMessage(type_, payload);
  ws.send(JSON.stringify(message));
}

function broadcast(self, type_, payload) {
  let message = createMessage(type_, payload);
  let messageStr = JSON.stringify(message);
  self.connections.forEach(ws => {
    try {
      ws.send(messageStr);
      return;
    } catch (exn) {
      self.connections.delete(ws);
      return;
    }
  });
}

function broadcastExecutionProgress(self, executionId, progress, message) {
  broadcast(self, "execution_progress", {
    execution_id: executionId,
    progress: progress,
    message: message,
    timestamp: Date.now().toString()
  });
}

let DashboardEvents = {
  make: make,
  createMessage: createMessage,
  sendToClient: sendToClient,
  broadcast: broadcast,
  broadcastExecutionProgress: broadcastExecutionProgress
};

export {
  WebSocket,
  DashboardEvents,
}
/* No side effect */
