// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DashboardEvents from "./DashboardEvents.res.js";

function make(events) {
  return {
    activeStreams: new Map(),
    events: events
  };
}

function subscribe(self, executionId, ws) {
  let s = self.activeStreams.get(executionId);
  let subscribers;
  if (s !== undefined) {
    subscribers = s;
  } else {
    let s$1 = new Set();
    self.activeStreams.set(executionId, s$1);
    subscribers = s$1;
  }
  subscribers.add(ws);
}

function streamLog(self, executionId, level, message) {
  let subscribers = self.activeStreams.get(executionId);
  if (subscribers !== undefined) {
    subscribers.forEach(ws => {
      try {
        return DashboardEvents.DashboardEvents.sendToClient(ws, "log_entry", {
          execution_id: executionId,
          level: level,
          message: message,
          timestamp: Date.now().toString()
        });
      } catch (exn) {
        subscribers.delete(ws);
        return;
      }
    });
    return;
  }
}

let StreamHandler = {
  make: make,
  subscribe: subscribe,
  streamLog: streamLog
};

export {
  StreamHandler,
}
/* No side effect */
