// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Jsonwebtoken from "jsonwebtoken";

let Types = {};

let Jwt = {};

let Http = {};

let Node = {
  Http: Http
};

let s = process.env.JWT_SECRET;

let jwtSecret = (typeof s === 'string') ? s : "wp-praxis-secret-change-in-production";

let s$1 = process.env.JWT_EXPIRES_IN;

let jwtExpiresIn = (typeof s === 'string') ? s$1 : "24h";

function extractToken(req) {
  let authHeader = req.headers.authorization;
  if (authHeader !== undefined) {
    if (authHeader.startsWith("Bearer ")) {
      return authHeader.substring(7, authHeader.length);
    } else {
      return authHeader;
    }
  }
}

async function verifyToken(token) {
  try {
    let decoded = Jsonwebtoken.verify(token, jwtSecret);
    let dict = Core__Option.getExn(Core__JSON.Decode.object(decoded), undefined);
    let match = dict["id"];
    let match$1 = dict["sub"];
    return {
      id: match !== undefined ? Core__Option.getOr(Core__JSON.Decode.string(match), "") : (
          match$1 !== undefined ? Core__Option.getOr(Core__JSON.Decode.string(match$1), "") : ""
        ),
      username: Core__Option.getOr(Core__Option.flatMap(dict["username"], Core__JSON.Decode.string), ""),
      roles: Core__Option.getOr(Core__Option.flatMap(dict["roles"], Core__JSON.Decode.array), []).map(v => Core__Option.getOr(Core__JSON.Decode.string(v), "")),
      permissions: Core__Option.getOr(Core__Option.flatMap(dict["permissions"], Core__JSON.Decode.array), []).map(v => Core__Option.getOr(Core__JSON.Decode.string(v), ""))
    };
  } catch (exn) {
    return;
  }
}

function generateToken(user) {
  let payload = Object.fromEntries([
    [
      "sub",
      user.id
    ],
    [
      "username",
      user.username
    ],
    [
      "roles",
      user.roles.map(prim => prim)
    ],
    [
      "permissions",
      user.permissions.map(prim => prim)
    ]
  ]);
  return Jsonwebtoken.sign(payload, jwtSecret, {
    expiresIn: jwtExpiresIn
  });
}

export {
  Types,
  Jwt,
  Node,
  jwtSecret,
  jwtExpiresIn,
  extractToken,
  verifyToken,
  generateToken,
}
/* s Not a pure module */
